import { getInstance, closeDb, db } from './src/database/db.js';
import { runMigrations } from './src/database/schema.js';
import {
  insertMessage,
  updateMessage,
  getMessage,
  getMessageBySource,
  getUnprocessed,
  updateProcessingStatus,
  createSignal,
  updateSignal,
  getSignal,
  getSignalByTicker,
  getSignalByCA,
  getActiveSignals,
  updateSignalStatus,
  addFollowUp,
  addPNL,
  createMapping,
  getMapping,
  getMappingBySource,
  updateMapping,
  insertPNL,
  getPNLsForSignal,
  logPublish,
  getPublishLog,
  cacheMedia,
  getMediaCache,
  getSources,
  getSource,
  updateSource,
  addSource,
  toggleSource,
  updateHealth,
  getHealth,
  insertLog,
  getLogs,
} from './src/database/repositories.js';

console.log('Verification test imports loaded successfully.');
